source: 1
parts: bolt

yolo:
  model: best_bolt_frame.pt
  imgsz: 640
  conf_thres: 0.4
  device: cuda

  save_txt: True
  save_crop: True
  save_txt: True
  save_format: 0
  save_csv: False
  save_conf: False

resnet:
  model: pth/bolt/bolt_best_resnet50.pth

  # if parts is door
  # high_model: ../classmodel/pth/door/model.pth
  # mid_model: ../classmodel/pth/door/model.pth
  # low_model: ../classmodel/pth/door/model.pth
  transform: "standard"

  config: ../classmodel/config.yaml
  batch_size: 16