source: 1
parts: bolt

yolo:
  model: modelfile/pt/best_bolt.pt
  imgsz: 640
  conf_thres: 0.4
  device: cuda

  save_txt: True
  save_crop: True
  save_txt: True
  save_format: 0
  save_csv: False
  save_conf: False

resnet:
  model: modelfile/pth/bolt/realbest_model.pth

  transform: "standard"

  config: ../classmodel/config.yaml
  batch_size: 16